### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by xHyroM** [freyacodes/Lavalink-Client#59]
Hello, when i have lavalink with plugin https://github.com/DuncteBot/skybot-lavalink-plugin everything works fine but my bot throw exception `Failed to load` but its loaded correctly.

This is message from exception: `Parameter specified as non-null is null: method me.xhyrom.mumblum.commands.Play$execute$1.trackLoaded, parameter track`

also happens with https://github.com/TopiSenpai/LavaSrc

**Comment by xHyroM** [comment]
this must be issue with this client because my friend uses https://npmjs.org/erela.js with JS and it works fine

**Comment by xHyroM** [comment]
> This client is a bit special as it integrates with lavaplayer
> 
> Basically you need the same source managers in the client as on the lavalink server
> 
> #57 adds support for adding those sources to the client

can you help me with this PR?

**Comment by xHyroM** [comment]
You are using JDA 4 https://github.com/freyacodes/Lavalink-Client/blob/configurable-decoding/build.gradle#L51 but my bot uses JDA 5 :/

**Comment by xHyroM** [comment]
i make fork and now everything works

**Comment by TopiSenpai** [comment]
I'm not sure on how the status is on both of those prs
I'm gonna mark this as solved for now
